App/HGPS.App/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using HGPS.App.Areas.HelpPage.Models;

namespace HGPS.App.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

App/HGPS.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- jQuery library -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>


    <link href="~/Content/css/StyleSheet.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/Main_Navigation.css" rel="stylesheet" />

</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a>
                </p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>

    <form id="MainForm" runat="server">

        <div id="content-wrapper">

            <div id="moon"></div>

            <div id="header"></div>
            <!--#include virtual="~/inc/Main_Navigation.asp" -->

            <div id="content-body">


                <div class="col-right bk-blk">

                    <asp:ContentPlaceHolder id="ColumnRight" runat="server">


                    </asp:ContentPlaceHolder>

                    <div style="margin-top:15px">
                        <a id="Android_Play_Store_Link" runat="server" alt="Android Play Store Link" href="https://play.google.com/store/apps/details?id=com.nester.HalloweenGPS"><img src="~/Content/images/Play_Store_Link.png" /></a>
                    </div>

                </div><!-- END col-right -->
                @RenderBody()


            </div><!-- END content-body -->


        </div><!--END content-wrapper -->

        <br class="clearfloat" />

        <div id="footer"></div>

    </form>



    <div class="witch">
        <img id="Witch1" alt="Haunted House Witch 1" src="~/Content/images/witch_rt_sm.png" />
    </div>

    <div class="witch2">
        <img id="Witch2" alt="Haunted House Witch 2" src="~/Content/images/witch_left_sm.png" />
    </div>


    @*@Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)*@

    <script type="text/javascript">

        function GoGoWitch() {

            debugger;

            $(document).ready(function () {

                $(".witch2").hide();
                $(".witch").delay('1').animate({ "margin-left": "+=80%" }, 5000);

                $(".witch").fadeOut();
                $(".witch2").delay('5300').fadeIn('slow');
                $(".witch2").animate({ "margin-left": "-=7%" }, 'slow');

            });
        };
    </script>

    <script type="text/javascript">
        GoGoWitch();
    </script>



    @*@Styles.Render("~/Content/css")*@
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-33301340-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>

</body>
</html>